[workspace]
members = [
    "src/reports",
    "src/realm",
    "src/app",
    "src/reports/macros",
    "client/lib"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

